"""Add order to Collection model

Revision ID: 510e1639e649
Revises: aa9cf5b6ad22
Create Date: 2025-10-28 00:00:50.996220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510e1639e649'
down_revision = 'aa9cf5b6ad22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_collection_parent_id', ['parent_id'], unique=False)
        batch_op.create_foreign_key('fk_collection_parent_id', 'collection', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_constraint('fk_collection_parent_id', type_='foreignkey') # Specify the name of the foreign key to drop
        batch_op.drop_index('ix_collection_parent_id')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('order')
    # ### end Alembic commands ###
