"""Initial migration

Revision ID: aa9cf5b6ad22
Revises: 
Create Date: 2025-10-25 22:42:56.777258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa9cf5b6ad22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_email', ['email'], unique=True)
        batch_op.create_index('ix_user_username', ['username'], unique=True)

    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.create_index('ix_collection_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_collection_user_id', ['user_id'], unique=False)

    op.create_table('leetcode_problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('leetcode_url', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('leetcode_problem', schema=None) as batch_op:
        batch_op.create_index('ix_leetcode_problem_difficulty', ['difficulty'], unique=False)
        batch_op.create_index('ix_leetcode_problem_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_leetcode_problem_title', ['title'], unique=True)

    op.create_table('leetcode_solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('solution_code', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('classification', sa.String(length=255), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['leetcode_problem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leetcode_solution', schema=None) as batch_op:
        batch_op.create_index('ix_leetcode_solution_approved', ['approved'], unique=False)
        batch_op.create_index('ix_leetcode_solution_problem_id', ['problem_id'], unique=False)
        batch_op.create_index('ix_leetcode_solution_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_leetcode_solution_user_id', ['user_id'], unique=False)

    op.create_table('snippet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snippet', schema=None) as batch_op:
        batch_op.create_index('ix_snippet_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_snippet_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snippet', schema=None) as batch_op:
        batch_op.drop_index('ix_snippet_user_id')
        batch_op.drop_index('ix_snippet_timestamp')

    op.drop_table('snippet')
    with op.batch_alter_table('leetcode_solution', schema=None) as batch_op:
        batch_op.drop_index('ix_leetcode_solution_user_id')
        batch_op.drop_index('ix_leetcode_solution_timestamp')
        batch_op.drop_index('ix_leetcode_solution_problem_id')
        batch_op.drop_index('ix_leetcode_solution_approved')

    op.drop_table('leetcode_solution')
    with op.batch_alter_table('leetcode_problem', schema=None) as batch_op:
        batch_op.drop_index('ix_leetcode_problem_title')
        batch_op.drop_index('ix_leetcode_problem_timestamp')
        batch_op.drop_index('ix_leetcode_problem_difficulty')

    op.drop_table('leetcode_problem')
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_index('ix_collection_user_id')
        batch_op.drop_index('ix_collection_timestamp')

    op.drop_table('collection')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_username')
        batch_op.drop_index('ix_user_email')

    op.drop_table('user')
    # ### end Alembic commands ###
